### ISSUE TITLE
Clean up Pictures 

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/data_team#12]
clean up all headshots in column D.
Export as 250x250 png.

https://docs.google.com/spreadsheets/d/1-akDARiGj7Lj9t5Wrivv5dyOngJMqtfWqxGSwnSHgZ4/edit#gid=2141158460

**Comment by ehab-hassan** [comment]
![Boris_Fahrnberger](https://user-images.githubusercontent.com/10484295/65855099-9c496f00-e35e-11e9-8112-8661788f68ff.jpg)
![bалентин_kоробко](https://user-images.githubusercontent.com/10484295/65855100-9c496f00-e35e-11e9-9631-4bc9ce290366.jpg)
![Can_Efe_Aydog](https://user-images.githubusercontent.com/10484295/65855101-9ce20580-e35e-11e9-8237-905a4e693af9.jpg)
![Colin_Baker](https://user-images.githubusercontent.com/10484295/65855102-9ce20580-e35e-11e9-89a8-28c19a9af7f8.jpg)
![Jeroen_Burks](https://user-images.githubusercontent.com/10484295/65855103-9d7a9c00-e35e-11e9-81b4-a42f140bfac5.jpg)
![Jonas_De_Zitter](https://user-images.githubusercontent.com/10484295/65855104-9ce20580-e35e-11e9-9f9d-47bb863d34dd.jpg)
![Josef_Ehrenhoefer](https://user-images.githubusercontent.com/10484295/65855106-9d7a9c00-e35e-11e9-821f-c1fc76ca746c.jpg)
![Katja_Luik](https://user-images.githubusercontent.com/10484295/65855107-9d7a9c00-e35e-11e9-81ff-4ca88afc58e2.jpg)
![Otto_Bauer](https://user-images.githubusercontent.com/10484295/65855108-9e133280-e35e-11e9-8175-6d24dafc3f56.jpg)
![Peter_Kraft](https://user-images.githubusercontent.com/10484295/65855109-9e133280-e35e-11e9-9502-2f6e84cda5b4.jpg)
![Roberto_Pesce](https://user-images.githubusercontent.com/10484295/65855110-9e133280-e35e-11e9-82a4-0a2ffde09c51.jpg)
