### ISSUE TITLE
go over list and make sure good enough

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/data_team#13]
- every one there
- everyone has why threefold filled in
- everyone means jimber, codescalers, veda, threefold
- make sure companies are properly filled in

**Comment by VonSub** [comment]
https://docs.google.com/spreadsheets/u/1/d/1tYVvIHUgmXd9Y3bcupJrWAtNUUTV-z0OEe6H9IXSDtc/edit?usp=drive_web&ouid=109781418176432807655

need to relais to all "N's" what needs changes.

**Comment by VonSub** [comment]
These need updates: See sheet to what needs updating.

- [x] ahmed_el_sayed
- [x] ahmed_hanafy
- [x] abdelrahman_ghanem
- [x] abdelrahman_hussein
- [x] abdul_rehman
- [x] adnan_fatayerji
- [x] ahmed_siddique
- [x] ahmed_thabet
- [x] ali_chaddad
- [x] amparo_miguel
- [x] andreas_hartl
- [x] andrew_ayoub
- [x] ashraf_fouda
- [x] atef_nazmy
- [x] bishoy_mikhaiel
- [x] bola_e_nasr
- [x] chris_hutton
- [x] christophe_de_carvalho_pereira_martins
- [x] daniela_nikolova
- [x] didem_gordon
- [x] dieter_legat
- [x] dina_adbelrahman
- [x] dina_magdy
- [x] dylan_verstraete
- [x] ehab_hassan
- [x] evon_yacoub
- [x] glen_de_cauwsemaecker
- [x] gloria_anne
- [x] hamdy_farag
- [x] isabelle_peeters
- [x] islam_taha
- [x] jan_de_landtsheer
- [x] jo_de_boeck
- [x] john_keir
- [x] jonas_delrue
- [x] joris_vermeulen
- [x] kristof_de_spiegeleer
- [x] lee_smet
- [x] lucia_groenfelt
- [x] lucie_nguyen
- [x] manu_de_poorter
- [x] mariza_kain
- [x] maxime_daniel
- [x] muhamad_azmy
- [x] nayer_sobhy
- [x] nickolay_babenko
- [x] olivia_jurado
- [x] owen_kemp
- [x] peter_nashaat
- [x] peter_van_der_henst
- [x] pierre_van_hoorebeke
- [x] ragheb_abushahba
- [x] ramez_saeed
- [x] rana_hassan
- [x] reem_khamis
- [x] rob_van_mieghem
- [x] roel_van_sabben
- [x] samar_adel
- [x] samir_hosny
- [x] sarah_boctor
- [x] simin_gerards
- [x] sophie_de_maesschalck
- [x] stela_suils_cuesta
- [x] virgil_ilian
- [x] weynand_kuijpers
- [x] yves_kerwyn
