### ISSUE TITLE
clean up photo Liliana Carrillo

### ISSUE THREAD

**Issue by lilianacarrillo** [threefoldfoundation/data_team#4]
Dear @VonSub,
Could you please clean up the background of my photo?
Thanks!

**Comment by ehab-hassan** [comment]
![Lillana-carrillo](https://user-images.githubusercontent.com/10484295/56432709-b3bffe80-62ce-11e9-8751-84e3f14dd2e4.jpg)
done :)

**Comment by lilianacarrillo** [comment]
Thanks :)

**Comment by VonSub** [comment]
when done please upload in the right map @ehab-hassan and close the issue. Thanks for the quick work!
