### ISSUE TITLE
Raphael Zöscher

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/data_team#42]
Based in : St.Lorenzen, Austria

I am farmer in double sense - as a breeder of horses and as a part of the Threefold-grid. I am absolutely convinced about the Threefold technology and I want to become a Threefold speaker to share this revolutionary idea with people in Austria, Italy and France.

My interests in Threefold lay at multiple layers from application development, blockchain to helping in social media engagement and marketing as well.

**Comment by VonSub** [comment]
![Uploading IMG-20181117-WA0014 - Raphael Zöscher.jpg…]()

**Comment by ehab-hassan** [comment]
@VonSub image not working can u send it again or by telegram

**Comment by ehab-hassan** [comment]
done
