### ISSUE TITLE
Please clean up Sam Taggart picture

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/data_team#8]
Please clean up Sam Taggart picture found in unprocessed pictures folder. Shouldn't need much. Thanks!

**Comment by VonSub** [comment]
thx @samtaggart we're on the case

**Comment by samtaggart** [comment]
Thanks – I did upload a "processed" version in my folder but wasn't sure if it fit the specifications.

**Comment by ehab-hassan** [comment]
done
https://github.com/threefoldfoundation/data_team/tree/master/team/sam_taggart
